import Foundation

public struct BRHandshakeDeviceInfo: Equatable, Sendable { public var uuid: String; public init(uuid: String = "") { self.uuid = uuid } }
public struct BRHandshakeAppInfo: Equatable, Sendable { public var time: Int64; public var uuid: String; public init(time: Int64 = Int64(Date().timeIntervalSince1970), uuid: String = UUID().uuidString) { self.time = time; self.uuid = uuid } }
public struct BRDeviceDetailInfo: Equatable, Sendable { public var name: String; public var sn: String; public var uuid: String; public var brand: String; public var model: String; public var deviceVersion: String; public var isAudioRecorded: String; public var screen: String; public var wifiSsid: String; public init(name: String = "", sn: String = "", uuid: String = "", brand: String = "", model: String = "", deviceVersion: String = "", isAudioRecorded: String = "0", screen: String = "no", wifiSsid: String = "") { self.name = name; self.sn = sn; self.uuid = uuid; self.brand = brand; self.model = model; self.deviceVersion = deviceVersion; self.isAudioRecorded = isAudioRecorded; self.screen = screen; self.wifiSsid = wifiSsid } }
public struct BRStorageCapacityInfo: Equatable, Sendable { public var unit: String; public var totalCapacity: Int64; public var opusCapacity: Int64; public var wavCapacity: Int64; public var freeCapacity: Int64; public var otherCapacity: Int64; public init(unit: String = "KBytes", totalCapacity: Int64 = 0, opusCapacity: Int64 = 0, wavCapacity: Int64 = 0, freeCapacity: Int64 = 0, otherCapacity: Int64 = 0) { self.unit = unit; self.totalCapacity = totalCapacity; self.opusCapacity = opusCapacity; self.wavCapacity = wavCapacity; self.freeCapacity = freeCapacity; self.otherCapacity = otherCapacity } }
public struct BRDeviceVersionInfo: Equatable, Sendable { public var brand: String; public var model: String; public var deviceVersion: String; public var softwareVersion: Int; public var softwareVersionPatch: Int; public var wifiSoftwareVersion: Int; public var wifiSoftwareVersionPatch: Int; public var wifiSsid: String; public init(brand: String = "", model: String = "", deviceVersion: String = "", softwareVersion: Int = 0, softwareVersionPatch: Int = 0, wifiSoftwareVersion: Int = 0, wifiSoftwareVersionPatch: Int = 0, wifiSsid: String = "") { self.brand = brand; self.model = model; self.deviceVersion = deviceVersion; self.softwareVersion = softwareVersion; self.softwareVersionPatch = softwareVersionPatch; self.wifiSoftwareVersion = wifiSoftwareVersion; self.wifiSoftwareVersionPatch = wifiSoftwareVersionPatch; self.wifiSsid = wifiSsid } }
public struct BRScanFilter: Equatable, Sendable { public var namePrefix: String?; public var serviceUUIDs: [UUID]; public var timeout: TimeInterval?; public init(namePrefix: String? = nil, serviceUUIDs: [UUID] = [BRGattUUIDs.advertisementService], timeout: TimeInterval? = nil) { self.namePrefix = namePrefix; self.serviceUUIDs = serviceUUIDs; self.timeout = timeout } }
public struct BRDiscoveredDevice: Equatable, Sendable { public var identifier: String; public var name: String?; public var sn: String?; public var rssi: Int; public var serviceUUIDs: [UUID]; public init(identifier: String, name: String? = nil, sn: String? = nil, rssi: Int = 0, serviceUUIDs: [UUID] = []) { self.identifier = identifier; self.name = name; self.sn = sn; self.rssi = rssi; self.serviceUUIDs = serviceUUIDs } }
public struct BRConnectedDevice: Equatable, Sendable { public var identifier: String; public var name: String?; public var detailInfo: BRDeviceDetailInfo?; public init(identifier: String, name: String? = nil, detailInfo: BRDeviceDetailInfo? = nil) { self.identifier = identifier; self.name = name; self.detailInfo = detailInfo } }
public struct BRBlueConnectInfo: Equatable, Sendable { public var device: BRConnectedDevice; public var handshakeInfo: BRDeviceDetailInfo?; public init(device: BRConnectedDevice, handshakeInfo: BRDeviceDetailInfo? = nil) { self.device = device; self.handshakeInfo = handshakeInfo } }
public struct BRBoundDeviceInfo: Codable, Equatable, Sendable { public var deviceName: String; public var deviceSN: String; public var deviceUUID: String; public var appUUID: String; public var peripheralIdentifier: String; public var cardMac: String { peripheralIdentifier }; public init(deviceName: String = "", deviceSN: String, deviceUUID: String = "", appUUID: String, peripheralIdentifier: String = "") { self.deviceName = deviceName; self.deviceSN = deviceSN; self.deviceUUID = deviceUUID; self.appUUID = appUUID; self.peripheralIdentifier = peripheralIdentifier } }
public struct BRDisconnectInfo: Equatable, Sendable { public var deviceIdentifier: String?; public var reason: String?; public var isUserInitiated: Bool; public init(deviceIdentifier: String? = nil, reason: String? = nil, isUserInitiated: Bool = false) { self.deviceIdentifier = deviceIdentifier; self.reason = reason; self.isUserInitiated = isUserInitiated } }
public struct BRWifiHotspotInfo: Equatable, Sendable { public var ssid: String; public var password: String; public var deviceUUID: String; public init(ssid: String = "", password: String = "", deviceUUID: String = "") { self.ssid = ssid; self.password = password; self.deviceUUID = deviceUUID } }
public struct BRWifiConnectInfo: Equatable, Sendable { public var hotspot: BRWifiHotspotInfo; public var state: BRWifiState; public init(hotspot: BRWifiHotspotInfo, state: BRWifiState = .connectedToDeviceHotspot) { self.hotspot = hotspot; self.state = state } }
public struct BRSocketStatus: Equatable, Sendable { public var isConnected: Bool; public var rawStatus: Int; public init(isConnected: Bool = false, rawStatus: Int = 0) { self.isConnected = isConnected; self.rawStatus = rawStatus } }
public struct BRWifiResumeInfo: Equatable, Sendable { public var fileName: String; public var index: Int; public var crc: UInt16; public init(fileName: String, index: Int = 0, crc: UInt16 = 0) { self.fileName = fileName; self.index = index; self.crc = crc } }
public struct BRAudioFileInfo: Equatable, Sendable { public var file: String; public var size: Int64; public var createTime: Int64; public var durationMs: Int64; public var type: Int; public var index: Int; public var toggleSwitch: Int; public var fileType: String; public var deleteFlag: Int; public init(file: String = "", size: Int64 = 0, createTime: Int64 = 0, durationMs: Int64 = 0, type: Int = 0, index: Int = 0, toggleSwitch: Int = 0, fileType: String = "Normal", deleteFlag: Int = 0) { self.file = normalizedOpusFileName(file); self.size = size; self.createTime = createTime; self.durationMs = durationMs; self.type = type; self.index = index; self.toggleSwitch = toggleSwitch; self.fileType = fileType; self.deleteFlag = deleteFlag } }
public struct BRAudioFileList: Equatable, Sendable { public var fileNum: Int; public var files: [BRAudioFileInfo]; public init(fileNum: Int = 0, files: [BRAudioFileInfo] = []) { self.fileNum = fileNum; self.files = files } }
public struct BRRecordStartInfo: Equatable, Sendable { public var file: String; public var createTime: Int64; public var toggleSwitch: Int; public var fileType: String; public var error: String?; public init(file: String = "", createTime: Int64 = 0, toggleSwitch: Int = 0, fileType: String = "Normal", error: String? = nil) { self.file = normalizedOpusFileName(file); self.createTime = createTime; self.toggleSwitch = toggleSwitch; self.fileType = fileType; self.error = error } }
public struct BRRecordStatus: Equatable, Sendable { public var isRecording: Bool; public var currentFile: String?; public var rawStatus: Int; public init(isRecording: Bool = false, currentFile: String? = nil, rawStatus: Int = 0) { self.isRecording = isRecording; self.currentFile = currentFile; self.rawStatus = rawStatus } }
public struct BRRecordStopResult: Equatable, Sendable { public var startInfo: BRRecordStartInfo?; public var crc: UInt16?; public var stopType: Int; public var realTimeSyncResult: BRRealTimeSyncResult?; public init(startInfo: BRRecordStartInfo? = nil, crc: UInt16? = nil, stopType: Int = 0, realTimeSyncResult: BRRealTimeSyncResult? = nil) { self.startInfo = startInfo; self.crc = crc; self.stopType = stopType; self.realTimeSyncResult = realTimeSyncResult } }
public struct BRFileSyncProgress: Equatable, Sendable { public var file: String; public var receivedBytes: Int64; public var totalBytes: Int64; public var lastFrameIndex: Int; public init(file: String, receivedBytes: Int64 = 0, totalBytes: Int64 = 0, lastFrameIndex: Int = -1) { self.file = file; self.receivedBytes = receivedBytes; self.totalBytes = totalBytes; self.lastFrameIndex = lastFrameIndex } }
public struct BRSingleFinishResult: Equatable, Sendable { public var fileInfo: BRAudioFileInfo; public var localFile: URL; public var success: Bool; public var crc: UInt16; public init(fileInfo: BRAudioFileInfo, localFile: URL, success: Bool, crc: UInt16) { self.fileInfo = fileInfo; self.localFile = localFile; self.success = success; self.crc = crc } }
public struct BRRealTimeSyncResult: Equatable, Sendable { public var file: String; public var localFile: URL?; public var success: Bool; public var crc: UInt16?; public init(file: String, localFile: URL? = nil, success: Bool = false, crc: UInt16? = nil) { self.file = file; self.localFile = localFile; self.success = success; self.crc = crc } }
public struct BRFlashIdeaStartInfo: Equatable, Sendable { public var file: String; public var createTime: Int64; public var error: String?; public init(file: String = "", createTime: Int64 = 0, error: String? = nil) { self.file = normalizedOpusFileName(file); self.createTime = createTime; self.error = error } }
public struct BRFlashIdeaStartResult: Equatable, Sendable { public var startInfo: BRFlashIdeaStartInfo?; public var errorCode: Int; public var errorMessage: String?; public init(startInfo: BRFlashIdeaStartInfo? = nil, errorCode: Int = 0, errorMessage: String? = nil) { self.startInfo = startInfo; self.errorCode = errorCode; self.errorMessage = errorMessage } }
public struct BRFlashIdeaEndResult: Equatable, Sendable { public var info: BRFlashIdeaStartInfo?; public var crc: UInt16?; public var errorCode: Int; public var errorMessage: String?; public var realTimeSyncResult: BRRealTimeSyncResult?; public init(info: BRFlashIdeaStartInfo? = nil, crc: UInt16? = nil, errorCode: Int = 0, errorMessage: String? = nil, realTimeSyncResult: BRRealTimeSyncResult? = nil) { self.info = info; self.crc = crc; self.errorCode = errorCode; self.errorMessage = errorMessage; self.realTimeSyncResult = realTimeSyncResult } }
public enum BRFlashIdeaStatus: Equatable, Sendable { case idle; case start(BRFlashIdeaStartInfo); case stop(BRFlashIdeaEndResult); case error(String) }
public struct BRFileMarkResult: Equatable, Sendable { public var type: Int; public var time: Int64; public init(type: Int = 0, time: Int64 = 0) { self.type = type; self.time = time } }
public struct BREarphoneScanResult: Equatable, Sendable { public var status: Int; public var name: String; public var cod: Int; public var rssi: Int; public var mac: String; public init(status: Int = 0, name: String = "", cod: Int = 0, rssi: Int = 0, mac: String = "") { self.status = status; self.name = name; self.cod = cod; self.rssi = rssi; self.mac = mac } }
public struct BREarphoneModeSetResult: Equatable, Sendable { public var commandAvailable: Bool; public var earphoneAction: Int; public var phoneAction: Int; public init(commandAvailable: Bool = false, earphoneAction: Int = 0, phoneAction: Int = 0) { self.commandAvailable = commandAvailable; self.earphoneAction = earphoneAction; self.phoneAction = phoneAction } }
public struct BREarphoneConnectionStatusResult: Equatable, Sendable { public var classicBluetoothEnabled: Bool; public var earphoneStatus: Int; public var phoneStatus: Int; public init(classicBluetoothEnabled: Bool = false, earphoneStatus: Int = 0, phoneStatus: Int = 0) { self.classicBluetoothEnabled = classicBluetoothEnabled; self.earphoneStatus = earphoneStatus; self.phoneStatus = phoneStatus } }
public struct BREarphoneHistoryMacResult: Equatable, Sendable { public var earphoneMac: String; public var phoneMac: String; public init(earphoneMac: String = "", phoneMac: String = "") { self.earphoneMac = earphoneMac; self.phoneMac = phoneMac } }
public enum BROtaChipType: UInt8, Equatable, Sendable { case ble = 0x01; case wifi = 0x02 }
public struct BROtaPackageInfo: Equatable, Sendable { public var fileURL: URL; public var packetSize: Int; public var chipType: BROtaChipType; public var version: Int; public var versionPatch: Int; public init(fileURL: URL, packetSize: Int = 40 * 1024, chipType: BROtaChipType, version: Int = 0, versionPatch: Int = 0) { self.fileURL = fileURL; self.packetSize = packetSize; self.chipType = chipType; self.version = version; self.versionPatch = versionPatch } }
public struct BROtaPackageSetInfo: Equatable, Sendable { public var blePackage: BROtaPackageInfo; public var wifiPackage: BROtaPackageInfo; public init(blePackage: BROtaPackageInfo, wifiPackage: BROtaPackageInfo) { self.blePackage = blePackage; self.wifiPackage = wifiPackage } }
public enum BROtaStage: String, Equatable, Sendable { case idle; case started; case packageStart; case packageData; case packageEnd; case writing; case finished }
public struct BROtaProgress: Equatable, Sendable { public var stage: BROtaStage; public var chipType: BROtaChipType?; public var currentPacket: Int; public var totalPacket: Int; public var progress: Double; public init(stage: BROtaStage = .idle, chipType: BROtaChipType? = nil, currentPacket: Int = 0, totalPacket: Int = 0, progress: Double = 0) { self.stage = stage; self.chipType = chipType; self.currentPacket = currentPacket; self.totalPacket = totalPacket; self.progress = progress } }
public struct BROtaResult: Equatable, Sendable { public var success: Bool; public var errorCode: Int; public var errorMessage: String?; public init(success: Bool = false, errorCode: Int = 0, errorMessage: String? = nil) { self.success = success; self.errorCode = errorCode; self.errorMessage = errorMessage } }

func normalizedOpusFileName(_ file: String) -> String {
    let trimmed = file.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty, !trimmed.lowercased().hasSuffix(".opus") else { return trimmed }
    return "\(trimmed).opus"
}

func inferAudioFileType(_ file: String) -> String {
    if file.hasPrefix("F") { return "FlashIdea" }
    if file.hasPrefix("E") { return "Earphone" }
    return "Normal"
}
